### ISSUE TITLE
Upgrade LoopBack to v3

### ISSUE THREAD

**Issue by beeman** [colmena/colmena#217]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

The API need to upgrade to LoopBack v3

**Comment by Praggie** [comment]
Hi @beeman any idea when colmena will be upgraded to LoopBack v3. Actually I am interested in using some of the features (Mulitple user models support ) of LoopBack 3 in my SaaS kind of Project. so wanted to know what kind of timelines I should keep in mind? Also Domain Concepts in current colmena seems to be similar to Organization concept in multiple user model described in LoopBack 3 documentation? will after loopback upgrade, domain concept in colmena will be based on it? Let me know what are your thoughts regarding this.  
[(https://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#access-control-with-multiple-user-models)]

**Comment by beeman** [comment]
Hi @Praggie - I've just started working on support for version 3 in this branch: https://github.com/colmena/colmena/tree/beeman/upgrade-loopback . I hope to land it within a few days.

Feel free to give it a test and leave any feedback.

**Comment by beeman** [comment]
Master now uses LoopBack 3 👍
